---
title: "The Canadian Arctic Vegetation Archive and Classification"
subtitle: "Ecosystem Classification of the Canadian Arctic"
author: "William H MacKenzie"
execute:
  echo: false
  warning: false
  error: false
  #cache: true
format: PrettyPDF-pdf
  #pdf:
    #fig-pos: H
    #documentclass: scrartcl
    #papersize: letter
editor: visual
header-includes:
 \usepackage{booktabs}
 \usepackage{longtable}
 \usepackage{array}
 \usepackage{multirow}
 \usepackage[table]{xcolor}
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}
---

```{r packages}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

require(tidyverse)
require(DBI) #loads odbc as well
require(data.table)
require(devtools)
require(knitr)
require(sf)
require(ggmap)
require(mapview)
require(mapdeck)
require(leaflet)
require(RColorBrewer)
require(colorspace)
require(flextable)
register_google("AIzaSyAosVE6MpjgQyNyG2NUcO4IsiKt7kd_eos")
```

```{r import data}

```

## Proposed geographic areas for classification field guides.
